version: "3"

services:
  postgres-compose:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: promoflash_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    container_name: postgres
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - promoflash-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: promoflash
    environment:
      - PORT:${PORT}
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres-compose
    volumes:
      - .:/app
    networks:
      - promoflash-network

networks:
  promoflash-network:
    driver: bridge
