version: '3.8'

services:
  db:
    image: postgres:15.4-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    networks:
      - promoflash-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always
    networks:
      - promoflash-network

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: promoflash_app
#     environment:
#       - PORT:${PORT}
#     env_file:
#       - .env
#     ports:
#       - '3000:3000'
#     depends_on:
#       - db
#     volumes:
#       - .:/app
#       - /app/node_modules
#     networks:
#       - promoflash-network

networks:
  promoflash-network:
    driver: bridge
